name: chamada_digital
description: A new Flutter project
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sembast: ^3.7.1+3
  geolocator: ^12.0.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.0.11  # Adiciona essa linha para incluir path_provider
  path: ^1.8.2  # Adiciona esta linha para incluir a dependência 'path'
  logging: ^1.0.2 # Adiciona esta linha para incluir a dependência de logging

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
